### PR TITLE
Documentation for hosting Posit tools on CloudCIX VMs

### PR DESCRIPTION
**Pull request by modalaigh**
Additions are as follows:
- Added guides on hosting RStudio server and Shiny apps on VMs
- Removed some duplicate .rst files
- Fixed some minor typos and a broken YouTube link
- Add custom.css file to increase page width

### CODE REVIEW

**Comment by BarryDigby** [comment]
Nice work! 

I've added a `.readthedocs.yaml` file to root and updated the `docs/source/conf.py` and `docs/source/requirements.txt` files to make the builds on RTD pass. 

I've added you as a collaborator to this repository and the corresponding Read the Docs project (m.odalaigh1@univ....ie?) - so you can implement changes yourself 😄

**Comment by BarryDigby** [comment]
Couldn't add a non-user, sign up for RTD `https://readthedocs.org/dashboard/` and let me know your username

**Comment by modalaigh** [comment]
Cheers Barry, I've made an account on RTD (modalaigh)

**Comment by BarryDigby** [comment]
Added. Changes to the repository trigger builds, viewable here `https://readthedocs.org/projects/cloud-cix/builds/`. 

Run a git pull to add the files mentioned above to your local repo and you're all set

**Pull request merged**
